version: '2'
services:
  php:
    image: tommylau/php
    ports:
      - "9000:9000"
    volumes:
      - ./html:/srv/http:ro
    links:
      - db
  nginx:
    image: nginx:latest
    links:
      - php:stackphp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
  db:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./mysql/databases:/var/lib/mysql:rw
      - ./mysql/scripts:/var/scripts:rw
      - ./mysql/log:/var/log/mysql
    entrypoint: "/var/scripts/mysql-run.sh"
